## DEFINE VERSION
version: '3.4'

## DEFINE SERVICES
services:
  api:
    image: golang:1.21.3-bookworm 
    working_dir: /app
    environment:
      ENV: "DEVELOPMENT"
    volumes:
      - ./:/app
    networks:
      - go-api
    ports:
      - 8080:8080
  db:
    image: postgres:16.0-bookworm
    environment:
      POSTGRES_PASSWORD: "MyPassword"
    volumes:
      - PG_DATA:/var/lib/postgresql/data
    networks:
      - go-api
    ports:
      - 5432:5432
  redis:
    image: redis:7.2.1-bookworm
    #environment:      
    volumes:
      - REDIS_DATA:/data
    networks:
      - go-api
    ports:
      - 6379:6379

## DEFINE VOLUMES
volumes:
  PG_DATA:
  REDIS_DATA:

## DEFINE NETWORK
networks:
  go-api:
